# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.32.0"

  on_macos do
    on_intel do
      sha256 "98ab214ed386bc3c29e8ddd2ca69b48578f69223d80fa52e09a1e75f57439127"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b343aa4e0ee6b3b2a65261ff41475b5074442b1a7562179232d8c1ab66e074d1"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2786e19c54ff132c9856fcfc14e06f6904e77e4e190cb59e99b7fe7d8e747d88"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a7bcbe3942040bb9c4c040d409fc6cb0e5ed2623612601d4e5a828a0d21297de"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
