# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.39.0"

  on_macos do
    on_arm do
      sha256 "d0a27bc060d2843f1b6b76315483921aa20844770f08b65eb2a26b36a7140ce7"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d0ed01dc252fad58714eaef515d14c5e71baede7357ced68f535560020d9e32e"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ea68c9e211ef502aea93389e21d1ea6bac63745aa81b55a1c769f6c48ab17289"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3910f656678df9f115208d9f2ab4add9558fbf4fd5fbe04d2cc743f6d92d3fed"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
