# This file was generated by GoReleaser. DO NOT EDIT.
cask "canticle" do
  version "1.29.1"

  on_macos do
    on_intel do
      sha256 "8fccf9b9998327a20669e6717622ae3babd4c20ab0a3459aab848c92b9f9c536"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c06b95d9fca3992de54c881a58f6411f402ec997cca13f31efdf5a4c110a9c00"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "466071f22046658c55ec3413c09534a917a5ad7f47cb3d39ea40113578fad481"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f74599c419260fd24d2a7f385ef424d00fa82c7e68b7468c3a468fbec8706c7e"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "canticle"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "mxlrcgo-svc",
    ]

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
