# This file was generated by GoReleaser. DO NOT EDIT.
cask "mxlrcgo-svc" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "ccddf435773c79da9025f4c2cc9348e6487b813cdf3599f566ef3bb11857f280"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3de19f03e9ca1736b7b5b2681346869be71898c955d179d12fe291369645f472"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "16c837b74c43ad3f8a0e5bd75c6451476b8acdd144346067e83ff7d4c4b92a5d"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d550708bce9f41453769d65094080354c6dc70ea25d6382893875f9048e42df"
      url "https://github.com/sydlexius/canticle/releases/download/v#{version}/canticle_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mxlrcgo-svc"
  desc "Fetch synced lyrics from Musixmatch and save them as .lrc files"
  homepage "https://sydlexius.github.io/canticle/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "canticle"

  # No zap stanza required

  caveats <<~EOS
    Set your Musixmatch token via MUSIXMATCH_TOKEN or in the config file:
      ~/.config/mxlrcgo-svc/config.toml (XDG path)
      See config.example.toml for all available options.
  EOS
end
